url: https://nikkijohl.github.io
baseurl: ""

# Site settings
title: NIKKI JOHL
email: nikkijohl@gmail.com
description: "Nikki Johl, student design portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a883e0
  secondary: 52c0ff
  secondary-dark: 8c8c8c

# Team names, titles and social links
people:
- name: Nikki Johl
  pic: 2
  position:
  social:
    - title: twitter
      url: # http://twitter.com/nikkiontaglike/
    - title: instagram
      url: # http://instagram.com/nikkijohl/
    - title: linkedin
      url: # www.linkedin.com/in/nikkijohl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nikkiontaglike
  - title: facebook
    url: 
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/nikkijohl

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
